name: Jekyll Build
description: A GitHub Action for just building Jekyll web sites (no deployment)
runs:
  using: docker
  image: Dockerfile
inputs:
  destination_dir:
    description: Jekyll build/destination directory
    required: false
    default: _site
  source_dir:
    description: Jekyll source directory
    required: false
    default: ./
  add_nojekyll_tag:
    description: Whether to add a .nojekyll file to the destination directory
    required: false
    default: true
